name: Railway Auto Redeploy

on:
  schedule:
    - cron: '0 0 */28 * *'  # Runs every 28 days
  workflow_dispatch:
jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Login and Redeploy
        run: |
          railway login --apiKey ${{ secrets.RAILWAY_API_TOKEN }}
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --detach
          
